sudo: false
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
- npm install -g gulp
- npm install
- cd exampleSite

script:
- "$TRAVIS_BUILD_DIR/bin/hugo version"
- "$TRAVIS_BUILD_DIR/bin/hugo"
- gulp min-html --cwd .


before_deploy:
- cd $TRAVIS_BUILD_DIR
- mkdir -p release
- zip -r release/devopsdays-theme-$TRAVIS_TAG.zip . -x \*.git\* \*exampleSite\* appveyor.yml \*.travis.ci\* \*tests\* \*bin\* \*build\* \*release\* config.codekit3 \*bower_components\* bower.json gulpfile.js netlify.toml package.json STYLE.md *\node_modules\*

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: wXshcH1JIjlfxm95YXaZqHCMTDIB6DIkO48+h5AmnCDJh0G8ktgeWRyj4CSH6+AHDu5wljtCOonmEOF9Aj7GOtZT4eNch01A731Dtlc5taoPXHvEEdocGnCJOHRqzFdXhS/UziDV5QxCApeVDLLLGeC3nABANGBRPBiE+Gz+S16ba9oYXgHiRc3nYrJ/5BHcVrpI+S5LpgsdFiuusA1C9OdIIIcxoJvcovHqFZCGsmzUIBMKbgo/IeoZ8EqmyW+E+cwbYxA5ZVv9zeMZQy+VL/XNyhbfeZZh2dQAmBOTzcbjol22zsnOIx+5DxULMU3/YclN73ImDMPB8fPI9AgZkU3kLuGu5E0TRmvcGaOEkRM8x7Bhca3luTo9YwtIQ3nhj4fS65FMzw79vbH3qyZvYxlFZzVMakZT98ov3YUimk8U14IZqvk3jf3ffmSnixVc7kELrlnEHByMffihhdQ1vggecSxGImUA5QqdSU7mVv5fOgSMSYzelVBA4RN241bdyvDLHRwSLih9yD7biIjfog1wP+luoap3nQQLtU7Zv8CmxmZrDLMwdLmrKHVHXKGoFLnMzN121iTceMuCwPHdmCmZuSMSuXBPG+yTVY/tzSZV84tphiIS4iJvPD2yv9VBs79Yhlqs/3CVQ+FWPAUGgfCfVF2NdB41xar7Ik9wn/I=
  file: 'release/devopsdays-theme-$TRAVIS_TAG.zip'
  on:
    repo: devopsdays/devopsdays-theme
    tags: true
